
#' Perform a single diffusion mapping step.
#' 
#' @param a A sparseMatrix M by M adjacency matrix (connectivities) whose m,m'-th
#' entry indicates the similarity between cells m and m' in the graph
#' @param s A sparseMatrix M by N indicator matrix assigning the m-th cell to the
#' n-th sample from which it was drawn.
#' 
#' @note This function ignores distances and only uses unweighted connectivities
#' 
#' @returns A M by N sparseMatrix.
#' 
#' @keywords internal
diffuseStep <- function(a, s) {
    degrees <- Matrix::colSums(a) + 1
    s_norm <- s / degrees
    res <- (a %*% s_norm) + s_norm
    return(res) 
}

#' calculate kurtosis of the rows or columns of a sparseMatrix 
#' 
#' @name Kurtosis
#' 
#' @param x A sparseMatrix for which the row or column kurtosis should be calculated
#' @param margin An integer specifying the margin over which to calculate kurtosis
#' 1 for rows and 2 for columns.
#' 
#' @return the row- or column-wise kurtosis of x
#' @keywords internal
Kurtosis <- function(x, margin){
    stopifnot(is.numeric(margin) && length(margin) == 1)
    stopifnot(is.matrix(x) || isa(x, "Matrix"))
    if(margin == 1){
        mu <- Matrix::rowMeans(x)
        m2 <- Matrix::rowMeans(x^2)
        m3 <- Matrix::rowMeans(x^3)
        m4 <- Matrix::rowMeans(x^4)
    } else if(margin == 2){
        mu <- Matrix::colMeans(x)
        m2 <- Matrix::colMeans(x^2)
        m3 <- Matrix::colMeans(x^3)
        m4 <- Matrix::colMeans(x^4)
    } else {
        stop("'margin' only supports single dimension of a matrix (1 or 2).")
    }
    
    # Expanded 4th central moment: E[(X-mu)^4]
    central4 <- m4 - 4*mu*m3 + 6*mu^2*m2 - 3*mu^4
    sigma4 <- (m2 - mu^2)^2
    
    kurt <- central4 / sigma4
    return(kurt)
}

#' A prop.table alternative for sparseMatrices
#' 
#' @param x A sparseMatrix
#' @param margin A vector giving the margins to split by. E.g., for a matrix 1 
#' indicates rows, 2 indicates columns.
#' 
#' @note unlike [base::prop.table()] this function doesn't handle `marge = c(1,2)`
#' 
#' @returns A sparse proportion table for the given margin
#' 
#' @keywords internal
propTable <- function(x, margin){
    stopifnot(is.numeric(margin) && length(margin) == 1)
    stopifnot(is.matrix(x) || isa(x, "Matrix"))
    if(margin == 1){
        res <- Matrix::t(Matrix::crossprod(x, Matrix::Diagonal(x = 1 /  Matrix::rowSums(x))))
    } else if(margin == 2){
        res <- x %*% Matrix::Diagonal(x = 1 /  Matrix::colSums(x)) 
    } else {
        stop("Only margins 1 or 2 are supported.")
    }
    return(res)
}

#' calculate kurtosis accounting for batch
#' 
#' @param NAM A NAM matrix as calculated by 
#' @param batch A factor containing batch information
#' 
#' @returns a vector of kurtosis values for each row (cell) in NAM
#' @keywords internal
batchKurtosis <- function(NAM, batch) {
    bI <- Matrix::fac2sparse(batch)
    # mean batch NAM
    bNAM <- Matrix::t(bI %*% NAM) %*% Matrix::Diagonal(x = 1 / Matrix::rowSums(bI))
    res <- Kurtosis(bNAM, margin = 1)
    return(res)
}

#' Filter NAM based on batch level kurtosis
#'
#' @param NAM a sparseMatrix NAM generated by [buildNAM()]
#' @param batch A factor containing batch information
#' @param min.threshold A numeric scalar defining the minimum value which the 
#' threshold should take.\cr
#' Default: 6
#' 
#' @note min.threshold is 6 here, to keep functionality the same as initially 
#' written, but there is no mention of this in the paper.
#'
#' @returns A list containing the filtered NAM (NAM) and a logical vector indicating
#' which cells were kept (keep).
#' @keywords internal
qcNAM <- function(NAM, 
                  batch = NULL, 
                  min.threshold = 6) {
    N <- nrow(NAM)
    ## NOTE: added NULL check 
    if (is.null(batch) || length(unique(batch)) == 1) {
        message('Only one unique batch supplied to qc')
        keep <- rep(TRUE, ncol(NAM))
        res <- list(NAM = NAM, keep = keep)
    } else {
        kurtoses <- batchKurtosis(NAM, batch)
        threshold <- max(min.threshold, 2*median(kurtoses))
        message("Throwing out neighborhoods with batch kurtosis >= ", threshold)
        keep <- which(kurtoses < threshold)
        message("keeping ", length(keep), " neighborhoods")   
        res <- list(NAM = NAM[, keep, drop = FALSE], keep = keep)
    }
    return(res) 
}

#' remove batch effects (including continuous covariates)
#' 
#' @param NAM a sparseMatrix NAM generated by [buildNAM()]
#' @param covs.mat A matrix of covariates.\cr
#' Default NULL
#' @param batch A factor containing batch information.\cr
#' Default NULL
#' @param ridges A numeric vector of ridge penalties to try. If NULL, a default
#' set of ridges is used `c(1e5, 1e4, 1e3, 1e2, 1e1, 1e0, 1e-1, 1e-2, 1e-3, 1e-4, 0)`.\cr
#' Default NULL
#' @param threshold A numeric indicating median batch kurtosis below which to stop
#' updating ridges. \cr
#' Default: 6
#' @note assumes that covariates are not categorical
#' @note the scale function in R gives slightly different results than does 
#' similar function in python 
#' 
#' @returns A list containing the residuals NAM (NAM_), the annihilator matrix used to
#' remove unwanted effects (M), and teh approximate degrees of freedom (r).
#' 
#' @keywords internal
residNAM <- function(NAM, 
                     covs.mat = NULL, 
                     batch = NULL, 
                     ridges = NULL,
                     threshold = 6) {
    N <- nrow(NAM)
    NAM_ <- scale(NAM, center = TRUE, scale = FALSE)
    
    r <- 0
    I <- Matrix::Diagonal(n = N)
    # TODO: Handle multiple batch variables.
    if(!is.null(batch) && length(unique(batch)) != 1) {
        X <- model.matrix(~0+batch)
        r <- r + ncol(X)
        M <- I - X %*% solve(crossprod(X, X), Matrix::t(X))
        NAM_ <- M %*% NAM_ 
    } 
    if(!is.null(covs.mat)) {
        X <- scale(covs.mat)
        if(is.null(ridges)) {
            # TODO: test that this is a viable solution. 
            sv_max <- svd(X)$d[1]^2
            ridges <- c(sv_max * 10^seq(3, -3, length.out = 20), 0)
            # ridges <- c(1e5, 1e4, 1e3, 1e2, 1e1, 1e0, 1e-1, 1e-2, 1e-3, 1e-4, 0)            
        } 
        
        for(lambda in ridges) {
            L <- Matrix::Diagonal(n = ncol(covs.mat))
            H <- X %*% solve(crossprod(X, X) + lambda * L, Matrix::t(X))
            M <- I - H
            NAM_tmp <- M %*% NAM_
            kurtoses <- batchKurtosis(NAM_tmp, batch)
            message("with ridge ", lambda, " median batch kurtosis = ", median(kurtoses))
            if(median(kurtoses) <= threshold) {
                r <- r + sum(diag(H))
                NAM_ <- NAM_tmp
                break  
            }
        }
    }
    NAM_ <- scale(NAM_, center = FALSE, scale = TRUE)
    res <- list(NAM_ = NAM_, 
                M = M,
                r = r) 
    return(res)
}

#' Compute the singular-value decomposition of a NAM matrix.
#' 
#' @param NAM a sparseMatrix NAM generated by [buildNAM()]
#' @param n.pcs maximum number of components to use in the SVD. Passed to the `k`
#' parameter of [RSpectra::svds()]. If NULL or `n.pcs > .5 * min(dim(NAM))`
#' then the full svd is calculated. \cr
#' Default: NULL
#' 
#' @note svs are actually eigenvalues, not SVs. I squared them to be consistent 
#' with python code. 
#' @note original implementation actually computes dot product: why? 
#' @note svdNAM scales NAM columns, so this is correlation, not covariance
#' 
#' @returns A list containing the components of the SVD.
#' 
#' @keywords internal
svdNAM <- function(NAM, n.pcs = NULL) {
    if (is.null(n.pcs) || n.pcs > .5 * min(dim(NAM))) {
        svd_res <- svd(NAM)
    } else {
        svd_res <- RSpectra::svds(NAM, k = n.pcs)
    }
    
    U <- svd_res$u[, seq_len(n.pcs)]
    colnames(U) <- paste0('PC', seq_len(n.pcs))
    rownames(U) <- rownames(NAM)
    V <- svd_res$v[, seq_len(n.pcs)]
    colnames(V) <- paste0('PC', seq_len(n.pcs))
    rownames(V) <- colnames(NAM)
    
    res <- list(U = U, 
                svs = svd_res$d^2, 
                V = V)
    return(res)
}

#' Calculate Neighborhood Association Matrix (NAM) using diffusion mapping
#' 
#' @param data A rcna data object (list).
#' @param n.steps A numeric, the number of steps to take during the random walk. 
#' If NULL, then `kurt.delta` is checked at each step to decide whether or not 
#' to take the next step. \cr
#' Default: NULL
#' @param min.steps A numeric value controlling the minimum number of steps to take. \cr
#' Default: 3
#' @param max.steps A numeric value controlling the maximum number of steps to take. \cr
#' Default: 15
#' @param kurt.delta The minimum change in kurtosis between steps under which
#' the walk stops. \cr
#' Default: 3
#'
#' @note The original code had a bug here where `prevmedkurt <- medkurt` was 
#' updated before calculating `prevmedkurt - medkurt` and so only a single diffusion
#' step was performed.
#' 
#' @returns A sparseMatrix containing the NAM
#' 
#' @keywords internal
buildNAM <- function(data, 
                     n.steps = NULL, 
                     min.steps = 3L,
                     max.steps = 15L,
                     kurt.delta = 3, 
                     verbose = FALSE) {
    
    f <- as.formula(paste0("~ 0 + ", data$samplem_key))    
    s <- Matrix::sparse.model.matrix(f, data$obs)
    colnames(s) <- gsub(data$samplem_key, '\\1', colnames(s))
    rownames(s) <- data$obs[[data$obs_key]]
    s <- s[, data$samplem[[data$samplem_key]]] ## Necessary? 
    
    prevmedkurt <- Inf
    ## CHECK: number of iterations matches 
    for (i in seq_len(max.steps)) {
        s <- diffuseStep(data$connectivities, s)
        medkurt <- median(Kurtosis(propTable(s, margin = 2), margin = 1))
        # if n.steps is null then take at least 3 steps
        if (is.null(n.steps)) {
            kd <- prevmedkurt - medkurt
            if(verbose) message("Kurtosis change: ", kd, " at step ", i)
            if (kd < kurt.delta & i > min.steps) {
                message("stopping after ", i, " steps")
                break 
            }
            prevmedkurt <- medkurt
        } else if (i == n.steps) {
            break
        }
    }  
    
    snorm <- Matrix::t(propTable(s, margin = 2))
    rownames(snorm) <- data$samplem[[data$samplem_key]]
    colnames(snorm) <- data$obs[[data$obs_key]]
    return(snorm)
}

#' Build and decompose a neighborhood abundance matrix 
#' 
#' @param data a list containing: 
#' samplem = (sample-level metadata), 
#' obs = (cell-level metadata), 
#' connectivities  = (sparse symmetric weighted adjacency matrix),
#' samplem_key = (character string indicating the column in samplem uniquely identifying samples),
#' obs_key = (character string indicating the column in obs uniquely identifying cells),
#' N = nrow(samplem_df).
#' @param y A character string specifying the column in `data$samplem` where 
#' the variable of interest is stored.\cr
#' @param batches A character string denoting the column in `data$samplem` where
#' batch information is stored. Only a single batch variable is allowed. \cr
#' Default: NULL 
#' @param covs A character string or vector denoting the column(s) `data$samplem`
#' where continuous covariate information is stored.\cr
#' Default: NULL
#' @param n.steps Numeric scalar controlling the number of steps to take during 
#' the random walk.\cr
#' Default: NULL
#' @param min.steps = .\cr
#' Default: 3L
#' @param max.steps = .\cr
#' Default: 15L
#' @param kurtosis.delta = .\cr
#' Default: 3
#' @param min.batch.kurtosis = .\cr
#' Default: 6
#' @param max.frac.pcs The number of PCs to calculate for SVD. The minimum is 10 
#' and the maximum is the number of samples minus 1. \cr
#' Default: 0.15
#' @param ridges .\cr
#' Default: NULL
#' @param ridge.kurt.threshold .\cr
#' Default: NULL
#' @param suffix A character scalar for optionally adding a suffix to the output
#' components for unknown reasons. \cr
#' Default: ""
#' @param verbose Logical scalar controlling verbosity. \cr
#' Default: FALSE
#' @param ... Additional parameters passed to [buildNAM()].
#' @param filter.samples STUB. Not used currently.
#' 
#' @return A list containing the NAM and associated variables.
#' 
#' @export 
nam <- function(data, y,
                batches = NULL, 
                covs = NULL, 
                # random walk parameters passed to buildNAM
                n.steps = NULL, 
                min.steps = 3L,
                max.steps = 15L,
                kurtosis.delta = 3,
                # minimum batch kurtosis passed to qcNAM
                min.batch.kurtosis = 6,
                max.frac.pcs = 0.15, 
                # passed to residNAM
                ridges = NULL,
                ridge.kurt.threshold = 6,
                # general
                suffix = '',
                filter.samples = NULL,
                verbose = FALSE) {
    if(missing(data) || missing(y)){
        stop("missing parameters with no defaults.")
    }
    if(!is.null(n.steps) && n.steps > max.steps){
        max.steps <- n.steps
    }
    ## TODO: check inputs! 
    
    res <- list()
    ## TODO: Filtering should happen at top level, either during data object
    ##       build or as a helper to manipulate existing data object

    # TODO: it would be cleaner overall if nam accepted either a character string
    #       for top level use, or a model.matrix for internal use by association
    if (is.null(batches)) {
        batch_vec <- NULL
    } else {        
        # batches must be categorical or factor
        # TODO: handle multiple batches
        batch_vec <- dplyr::pull(data$samplem, dplyr::one_of(batches)) |> 
            as.factor()
    }
    if (is.null(covs)) {
        cov_mat <- NULL
    } else {
        # covariates must be numeric or factors
        cov_mat <- data$samplem[, covs, drop = FALSE] |> 
            as("sparseMatrix")
        # # covariates must be numeric or factors
        # cov_df <- data$samplem[, covs, drop = FALSE] 
        # cform <- paste0("~ 0 + ", paste0(colnames(cov_df), collapse = " + ")) |> 
        #     as.formula()
        # cov_mat <- Matrix::sparse.model.matrix(cform, cov_df)
    }
    
    if (verbose) message('Constructing NAM')
    NAM <- buildNAM(data, 
                    n.steps = n.steps, 
                    min.steps = min.steps,
                    max.steps = max.steps, 
                    kurt.delta = kurtosis.delta, 
                    verbose = verbose)
    if (verbose) message('QC-ing NAM')
    res_qc_nam <- qcNAM(NAM, batch = batch_vec, min.threshold = min.batch.kurtosis) 
    
    # y is returned in order to avoid recalculating NAM if not desired.
    # TODO: handle multiple y?
    y <- data$samplem[, y, drop = TRUE]
    if(is.character(y)){
        y <- as.numeric(as.factor(y))
    } else {
        y <- as.numeric(y)
    }
    res[['y']] <- y
    res[[paste0('NAM.T', suffix)]] <- Matrix::t(res_qc_nam[[1]])
    res[[paste0('keptcells', suffix)]] <- res_qc_nam[[2]]
    res[[paste0('_batches', suffix)]] <- batch_vec
    
    ## (3) Decompose NAM 
    ## TODO: check if double brackets appropriate for multiple covs and/or batches
    ## TODO: check with Y&L if covs should be numerical and batches categorical
    ## NOTE: don't really need a separate SVD function, since it can be done in one line
    if (verbose) message('Residualizing NAM')
    res_resid_nam <- residNAM(NAM, covs.mat = cov_mat, 
                              batch = batch_vec, 
                              ridges = ridges,
                              threshold = ridge.kurt.threshold)
    res[[paste0('_M', suffix)]] <- res_resid_nam$M
    res[[paste0('_r', suffix)]] <- res_resid_nam$r
    
    if (verbose) message('Decomposing NAM')
    n_pcs <- max(10, ceiling(max.frac.pcs * nrow(data$samplem)))
    n_pcs <- min(n_pcs, nrow(data$samplem) - 1) ## make sure you don't compute all SVs    
    res_svd_nam <- svdNAM(res_resid_nam$NAM_, n.pcs = n_pcs)
    res[[paste0('NAM_sampleXpc', suffix)]] <- res_svd_nam$U
    res[[paste0('NAM_svs', suffix)]] <- res_svd_nam$svs
    res[[paste0('NAM_varexp', suffix)]] <- res_svd_nam$svs / nrow(res_svd_nam$U) / nrow(res_svd_nam$V)
    res[[paste0('NAM_nbhdXpc', suffix)]] <- res_svd_nam$V
    
    ## TODO: save covs for later
    #     du['_covs'+suffix] = (np.zeros(0) if covs is None else covs)  
    #     res[[paste0('_covs', suffix)]]
    return(res)
}
