
#' Extract information from SingleCellExperiment object to create a CNA object
#' 
#' @param sce A SingleCellExperiment object. 
#' @param y A character string denoting the name of the variable to be 
#' tested for association.
#' @param sample.key A character string denoting the name of the sample-level 
#' identifier (e.g. DonorID). 
#' @param sample.vars A character string or vector specifying which columns of 
#' `colData(sce)` should be included. This should include any columns for batch
#' and covariates. 
#' @param knn.graph A KNN graph in `sparseMatrix` format, or the name of such a graph
#' stored in `colPair(sce)`. 
#' 
#' @returns An `rnca` data object (list)
#' 
#' @export 
createCNAListSCE <- function(sce, 
                             y,
                             sample.key, 
                             sample.vars = NULL, 
                             knn.graph) {
    if(any(c(missing(sce), missing(sample.key), missing(knn.graph)))){
        stop("Parameters missing with no default.")
    }
    if(!isa(knn.graph, "Matrix") && !(is.character(knn.graph) && length(knn.graph) == 1)){
        stop("'knn.graph' must be a square sparseMatrix with dims equal to 'ncol(sce)'",
             "or a character string")
    }
    if(isa(knn.graph, "Matrix")){
        if(!all(dim(knn.graph) == ncol(sce))){
            stop("'knn.graph' must be a square sparseMatrix with dims equal to 'ncol(sce)'")
        }
    } else if(is.character(knn.graph)){
        stopifnot(knn.graph %in% SingleCellExperiment::colPairNames(sce))
        graph <- SingleCellExperiment::colPair(sce, knn.graph, asSparse = TRUE)
    }
    
    sample.vars <- c(sample.key, sample.vars, y)
    stopifnot(all(sample.vars %in% colnames(SummarizedExperiment::colData(sce))))
    
    samplem_df <- SummarizedExperiment::colData(sce) |> 
        as.data.frame() |> 
        dplyr::select(dplyr::all_of(sample.vars)) |> 
        dplyr::distinct() |> 
        as.data.frame()
    n <- length(unique(samplem_df[, sample.key, drop = TRUE]))
    if(nrow(samplem_df) != n){
        stop("'sample.vars' must collapse to a unique value for each value in 'sample.key' ",
             "Please check that sample.vars are sample-level variables.")
    }
    rownames(samplem_df) <- NULL
    
    obs_df <- SummarizedExperiment::colData(sce)[, sample.key, drop = FALSE] |> 
        as.data.frame()
    obs_df$CellID <- rownames(obs_df)
    rownames(obs_df) <- NULL
    
    rcna_object <- list(
        samplem = samplem_df,
        obs = obs_df, 
        connectivities = graph,
        samplem_key = sample.key,
        obs_key = 'CellID',
        N = nrow(samplem_df)
    )
    return(rcna_object)
}

#' @rdname association
#' 
#' @param sce A SingleCellExperiment object. 
#' @param y A character string denoting the name of the variable to be 
#' tested for association.
#' @param sample.key String denoting the name of the sample-level identifier (e.g. DonorID). 
#' @param graph A character string specifying the name of the graph to pull from
#' the SCE object (stored in ) or an association sparseMatrix as generated by uwot.
#' @param batches Name of batch variable. Currently only one categorical variable allowed. 
#' @param covs Name(s) of other (numerical) covariates to control for. 
#' @param verbose A logical controlling the verbosity of the function.\cr
#' Default: FALSE
#' 
#' @returns The input `sce` with NAM embeddings stored in `reducedDim(sce, "CNA")`.
#' In addition `cna_ncorrs` as well as `cna_ncorrs_fdr05` and `cna_ncorrs_fdr10` 
#' (if any neighborhoods passed these significance thresholds) are added to the 
#' `colData` of the `sce`. The remaining components of the analysis are stored in 
#' `metadata(sce)$CNA` 
#' 
#' @export 
associationSCE <- function(sce, y, sample.key, graph, 
                           batches = NULL, 
                           covs = NULL, 
                           verbose = FALSE, 
                           ...){
    ## (1) format data 
    covs_keep <- y
    if (!is.null(batches)) {
        covs_keep <- c(covs_keep, batches)
    }
    if (!is.null(covs)) {
        covs_keep <- c(covs_keep, covs)
    }
    rcna_data <- createCNAListSCE(sce = sce, 
                                  y = y,
                                  sample.key = sample.key ,   
                                  sample.vars = covs_keep,   
                                  knn.graph = graph)  
    
    ## (2) do association
    cna_res <- association(data = rcna_data, 
                           y = y, 
                           batches = batches, 
                           covs = covs,
                           return.nam = TRUE,
                           verbose = verbose,
                           ...) 
    if(sum(cna_res$keptcells) == ncol(sce)){
        ## (3) save results 
        colnames(cna_res$NAM_nbhdXpc) <- paste0("NAMPC_", seq_len(ncol(cna_res$NAM_nbhdXpc)))
        SingleCellExperiment::reducedDim(sce, "CNA") <- cna_res$NAM_nbhdXpc
        
        # put the rest into metadata
        S4Vectors::metadata(sce)$CNA <- cna_res[!names(cna_res) %in% c("NAM_nbhdXpc", 
                                                                       "NAM_sampleXpc", 
                                                                       "NAM_svs", 
                                                                       "ncorrs")]
        # corrs goes into colData for easy plotting
        sce$cna_ncorrs <- cna_res$ncorrs[colnames(sce), , drop = TRUE]
        
        # NOTE: If threshold was NULL, then no cells passed the significance threshold 
        sce$cna_ncorrs_fdr05 <- rep(0, ncol(sce))
        if (!is.null(cna_res$fdr_5p_t)) {
            idx_passed <- which(abs(sce$cna_ncorrs) >= cna_res$fdr_5p_t)
            sce$cna_ncorrs_fdr05[idx_passed] <- sce$cna_ncorrs[idx_passed]
        }
        
        sce$cna_ncorrs_fdr10 <- rep(0, ncol(sce))
        if (!is.null(cna_res$fdr_10p_t)) {
            idx_passed <- which(abs(sce$cna_ncorrs) >= cna_res$fdr_10p_t)
            sce$cna_ncorrs_fdr10[idx_passed] <- sce$cna_ncorrs[idx_passed]
        }
    } else {
        warning("Some cells were filtered. All CNA results will be stored in metadata.")
        S4Vectors::metadata(sce)$CNA <- cna_res
    }
    
    
    return(sce)
}